include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    close_sinks: error
    missing_required_param: error
    missing_return: error
    parameter_assignments: warning
    todo: ignore
  exclude:
    - "**/*.g.dart"
    - build/**

# Rules on top of package:flutter_lints. Keep this list alphabetical.
linter:
  rules:
    - always_declare_return_types
    - always_put_control_body_on_new_line
    - always_use_package_imports
    - avoid_bool_literals_in_conditional_expressions
    - avoid_dynamic_calls
    - avoid_equals_and_hash_code_on_mutable_classes
    - avoid_escaping_inner_quotes
    - avoid_field_initializers_in_const_classes
    - avoid_redundant_argument_values
    - avoid_renaming_method_parameters
    - avoid_returning_null_for_void
    - avoid_slow_async_io
    - avoid_type_to_string
    - avoid_unused_constructor_parameters
    - avoid_void_async
    - cancel_subscriptions
    - cascade_invocations
    - cast_nullable_to_non_nullable
    - close_sinks
    - comment_references
    - deprecated_consistency
    - directives_ordering
    - eol_at_end_of_file
    - flutter_style_todos
    - join_return_with_assignment
    - leading_newlines_in_multiline_strings
    - missing_whitespace_between_adjacent_strings
    - no_adjacent_strings_in_list
    - no_default_cases
    - no_runtimeType_toString
    - noop_primitive_operations
    - only_throw_errors
    - parameter_assignments
    - prefer_asserts_in_initializer_lists
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_final_fields
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_if_elements_to_conditional_expressions
    - prefer_null_aware_method_calls
    - prefer_single_quotes
    - provide_deprecation_message
    - public_member_api_docs
    - sort_child_properties_last
    - sort_constructors_first
    - sort_unnamed_constructors_first
    - test_types_in_equals
    - throw_in_finally
    - tighten_type_of_initializing_formals
    - type_annotate_public_apis
    - unawaited_futures
    - unnecessary_lambdas
    - unnecessary_null_aware_assignments
    - unnecessary_null_checks
    - unnecessary_parenthesis
    - unnecessary_statements
    - unsafe_variance
    - use_is_even_rather_than_modulo
    - use_named_constants
    - use_raw_strings
    - use_setters_to_change_properties
    - use_super_parameters
    - use_test_throws_matchers
